let createdAt = new Date().getTime();
const tableData = [
  {
    projectCode: 'PRJ-01',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '7',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'In-Progress',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
  {
    projectCode: 'PRJ-02',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '7',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'Done',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
  {
    projectCode: 'PRJ-03',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '7',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'Submitted',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
  {
    projectCode: 'PRJ-04',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '7',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'Rejected',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
  {
    projectCode: 'PRJ-05',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '7',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'In-Progress',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
  {
    projectCode: 'PRJ-06',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '7',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'In-Progress',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
  {
    projectCode: 'PRJ-07',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '8',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'Done',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
  {
    projectCode: 'PRJ-08',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '7',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'Rejected',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
];
const sortOption = {};
class fakeData {
  constructor(size) {
    this.size = size || 2000;
    this.datas = [];
    this.sortKey = null;
    this.sortDir = null;
  }
  dataModel(index) {
    return tableData[index];
  }
  getObjectAt(index) {
    if (index < 0 || index > this.size) {
      return undefined;
    }
    if (this.datas[index] === undefined) {
      this.datas[index] = this.dataModel(index);
    }
    return this.datas[index];
  }
  getAll() {
    if (this.datas.length < this.size) {
      for (let i = 0; i < this.size; i++) {
        this.getObjectAt(i);
      }
    }
    return this.datas.slice();
  }

  getSize() {
    return this.size;
  }
  getSortAsc(sortKey) {
    sortOption.sortKey = sortKey;
    sortOption.sortDir = 'ASC';
    return this.datas.sort(this.sort);
  }
  getSortDesc(sortKey) {
    sortOption.sortKey = sortKey;
    sortOption.sortDir = 'DESC';
    return this.datas.sort(this.sort);
  }
  sort(optionA, optionB) {
    const valueA = optionA[sortOption.sortKey].toUpperCase();
    const valueB = optionB[sortOption.sortKey].toUpperCase();
    let sortVal = 0;
    if (valueA > valueB) {
      sortVal = 1;
    }
    if (valueA < valueB) {
      sortVal = -1;
    }
    if (sortVal !== 0 && sortOption.sortDir === 'DESC') {
      return sortVal * -1;
    }
    return sortVal;
  }
}
export default fakeData;
