import React from 'react';
import { Tabs, Row, Col, Card } from 'antd';
import Assignments from '@iso/containers/Assignments/Assignments';
import DisplayPageDetails from '@iso/containers/DisplayPageDetails/DisplayPageDetails';
import BasicStyle from './Payments.styles';

const paymentData = [
  {
    projectCode: 'PRJ-01',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '7',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'In-Progress',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
  {
    projectCode: 'PRJ-02',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '7',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'Done',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
  {
    projectCode: 'PRJ-03',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '7',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'Submitted',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
  {
    projectCode: 'PRJ-04',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '7',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'Rejected',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
  {
    projectCode: 'PRJ-05',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '7',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'In-Progress',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
  {
    projectCode: 'PRJ-06',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '7',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'In-Progress',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
  {
    projectCode: 'PRJ-07',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '8',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'Done',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
  {
    projectCode: 'PRJ-08',
    projectName: 'Bank',
    projectType: 'Bank',
    genre: 'Banking',
    vertical: 'Bank',
    experienceLevel: 'Omega',
    language: 'English',
    objective: 'for marketing',
    audience: 'Young',
    totalArticle: '7',
    dueDate: '25-12-2019',
    createdDate: '25-12-2019',
    status: 'Rejected',
    amount: '5000',
    articles: [
      {
        articleCode: 'ART-01',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-02',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-03',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-04',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-05',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-06',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
      {
        articleCode: 'ART-07',
        articleTopic: 'blog',
        word: '2000',
        status: 'Completed',
        keyword: 'java, api, aws, react',
        genre: 'Banking',
        vertical: 'Bank',
        refrence: 'news',
        description: 'Hello World',
        RemainingTime: '',
        deadline: '',
        transactionDate: '',
        transactionId: '',
        transactionAmount: '',
        transactionStatus: '',
        remarks: '',
        feedback: '',
        fileAttached: ['asd.doc'],
      },
    ],
  },
];
class Payments extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      paymentData: paymentData,
    };
    this.handleTabChange = this.handleTabChange.bind(this);
    this.handleStatusChange = this.handleStatusChange.bind(this);
  }

  handleStatusChange(val, row) {
    //console.log('lllllllllllll', val, row);
    //change the status here
  }

  handleTabChange(key) {
    console.log(key);
    switch (key) {
      case '2':
        this.setState({
          paymentData: paymentData.filter(
            item => item.status === 'In-Progress'
          ),
        });
        break;
      case '3':
        this.setState({
          paymentData: paymentData.filter(item => item.status === 'Submitted'),
        });
        break;
      case '4':
        this.setState({
          paymentData: paymentData.filter(item => item.status === 'Completed'),
        });
        break;
      case '5':
        this.setState({
          paymentData: paymentData.filter(item => item.status === 'Rejected'),
        });
        break;
      default:
        this.setState({
          paymentData: paymentData,
        });
        break;
    }
  }

  render() {
    const { TabPane } = Tabs;
    const { paymentData } = this.state;
    const { cardStyle, rowStyle, colStyle } = BasicStyle;
    return (
      <Card>
        <Row span={24} gutter={16} style={rowStyle}>
          <Col span={16} style={colStyle}>
            <Card hoverable={true} style={cardStyle}>
              <Tabs defaultActiveKey="1" onChange={this.handleTabChange}>
                <TabPane tab="All" key="1">
                  <Assignments
                    filters={false}
                    onStatusChange={this.handleStatusChange}
                    data={paymentData}
                  />
                </TabPane>
                <TabPane tab="Ongoing Assignments" key="2">
                  <Assignments
                    filters={false}
                    data={paymentData}
                    onStatusChange={this.handleStatusChange}
                  />
                </TabPane>
                <TabPane tab="Submitted by Portal" key="3">
                  <Assignments
                    filters={false}
                    data={paymentData}
                    onStatusChange={this.handleStatusChange}
                  />
                </TabPane>
                <TabPane tab="Completed" key="4">
                  <Assignments
                    filters={false}
                    data={paymentData}
                    onStatusChange={this.handleStatusChange}
                  />
                </TabPane>
                <TabPane tab="Rejected" key="5">
                  <Assignments
                    filters={false}
                    data={paymentData}
                    onStatusChange={this.handleStatusChange}
                  />
                </TabPane>
              </Tabs>
            </Card>
          </Col>

          <Col span={8} style={colStyle}>
            <Card hoverable={true} style={cardStyle}>
              <DisplayPageDetails />
            </Card>
          </Col>
        </Row>
      </Card>
    );
  }
}
export default Payments;
